#!/usr/bin/env bash
source r2d.config

if [ ! -d $out ]
then
    echo "Making directory "$out
    mkdir $out
fi

function doreplacements {
    for f in `cat $inputfile`
    do
        if [ -f $f ]
        then
            bf=`basename $f`
            count=`sed -n "\_[\w\./]*"$bf"_p" < $1 | wc -L`
            if [ $count -gt 0 ]
            then
                sed "\_"$bf"_s_[a-z\.0-9A-Z\/]*"$bf"_"$bf"_" < $1 > $out"tmp"
                mv $out"tmp" $1
            fi
        fi
    done
}

echo "Copying to "$out
for f in `cat $inputfile`
do
    bf=`basename $f`
    if [ -f $f ]
    then
    cp $f $out$bf
    else
        if [ ! -e $f ]
        then
            echo "Missing: "$f
        fi
    fi
done

echo Transforming...
flist=`ls $out`
for f in $flist
do
    if [ -f $out$f ]
    then
	    echo "Processing "$f
        doreplacements $out$f
    fi
done

echo "FINISHED"

source $tforms
