#!/bin/bash
source r2d.config

for f in `cat $inputfile`
do
	bf=`basename $f`
	echo $f": "$bf
	if [ -e $f ]
	then
	echo cp $f $out$bf
	cp $f $out$bf
	awk '{print basename $1}' $f
	else
	echo NE
	fi
done

echo "FINISHED"
ls ./live
